### PR TITLE
Fixing a couple of minor bugs and added new variable class

### PR DESCRIPTION
**Pull request by remidhum**
**Bug fixes:**

- fixed the apply_directionality function to properly obtain the forward and backward variables wanted.
- fixed the rebuilding of models without an objective function to now have a dummy one. 

**Enhancement:** 

- added a new class (ForwardBackwardUseVariable) to easily deal with inactive reactions in a model.

### CODE REVIEW

**Comment by remidhum** [comment]
The test fails because my 'fix' for the apply_directionality is due to the fact I pass the solution.raw directly instead of the solution object itself. 
I don't know if it is more elegant to deal with this use case or not. 
Please let me know what you think of it so I can make the appropriate changes to the PR (fix the test or revert the first commit).
Cheers :)

**Comment by remidhum** [comment]
I also notice that the `strip_from_integer_variables()` function takes advantage of the `rebuild_obj_from_dict()` function to not set an objective value for the sampling later on. 
This causes the commits in this PR to result not be able to sample properly. 

I now wonder whether the `strip_from_integer_variables()` should be modified to revert to what is expected of it or if the changes in `rebuild_obj_from_dict()` should be completely rethought.

**Comment by psalvy** [comment]
Hi @remidhum 
Thanks for these useful contributions !

> The test fails because my 'fix' for the apply_directionality is due to the fact I pass the solution.raw directly instead of the solution object itself.
> I don't know if it is more elegant to deal with this use case or not.

I think passing the solution object is more appropriate, as it is more high level. Alternatively you can write a check that verifies the type of the solution passed (DataFrame or solution object) and assigns the proper object to the solution variable. I would actually encourage this as it is more in accordance of what is done in cobra, pyTFA and ETFL.

> I also notice that the strip_from_integer_variables() function takes advantage of the rebuild_obj_from_dict() function to not set an objective value for the sampling later on.
> This causes the commits in this PR to result not be able to sample properly.

I am of the opinion that stripping from integer variable should not edit the objective function, and the user should provide their own ahead of time

**Comment by remidhum** [comment]
Thank you for your suggestion regarding the `apply_directionality()` function.
Hopefully the check is OK with you.

> I am of the opinion that stripping from integer variable should not edit the objective function, and the user should provide their own ahead of time

I agree with you.
It would seem however that I was wrong regarding the objective function. 
Quite confusingly, I cannot reproduce the error I was observing the other day...

**Pull request merged**
